Add mlflow logging of metrics for each category
ElefHead/yolov5 pull request #1
Opened 2022-09-04 23:34 UTC by teodora-petkova

Thank you really a lot for your branch and pull request  [#8261](https://github.com/ultralytics/yolov5/pull/8261) about mlflow logging!!

I have added a small option about logging the metrics for each category/class for every epoch as I did not see it available at the moment. I use it in my tests in order to analyze the progress of the metrics of each class and compare the separate metrics between runs, as well.

Here is a simple visualization for a few classes and their mAP@5.0 progression during all the epochs, that can be produced:
![example](https://user-images.githubusercontent.com/8216410/188337202-05e7a398-264e-475f-b2f1-ea23a6fdaf9e.PNG)

I am looking forward for your review! Thank you again!

2022-09-08 13:57 UTC, ElefHead commented
This is great! I'm taking a vacation at the moment and will review this PR on satuday. Thanks so much!

2022-11-15 12:36 UTC, teodora-petkova commented
Hi! Thank you! I have added a small change to take into account the case when the validation dataset does not contain examples from all classes. Also, I merged with the current state of the repository in order not to have any conflict with your base branch.
Is there something that I can help with? Or should I improve the pull request in some way?
Thank you a lot for you great work and help!

2022-11-15 19:38 UTC, ElefHead commented on val.py
> +        callbacks.run('on_val_end_compute_metrics', available_names, ap50, ap, f1, p, r)
I am gonna add this, but we might take it out if the repo maintainers don't want it -- wondering why no logging callbacks are present in the validation scripts.

2022-11-15 19:45 UTC, ElefHead requested changes

2022-11-15 19:45 UTC, ElefHead commented on utils/loggers/mlflow/mlflow_utils.py
> +        self.current_epoch = {}
Should be set to 0? 
and might conflict on resumes - let me play around with this over the weekend, think there's different ways to handle resumes already

2022-11-15 19:45 UTC, ElefHead commented on utils/loggers/__init__.py
>      def on_fit_epoch_end(self, vals, epoch, best_fitness, fi):
might need to handle `on_val_end` similar to how comet is handling it. Gonna implement that too.

2023-04-14 00:37 UTC, closed without merging